### ISSUE TITLE
capabilityDelegation and capabilityInvocation

### ISSUE THREAD

**Issue by troyronda** [trustbloc/sidetree-core-go#229] opened 2020-04-20 14:57 UTC
It would be good to have common support with did:key. [See spec](https://w3c-ccg.github.io/did-method-key/).

did:key has capabilityDelegation and capabilityInvocation.

Unfortunately these are unspecified in the sidetree spec.

**Comment by sandrask** [comment] 2020-04-29 13:23
Duplicate of #270

**Closed by sandrask** 2020-04-29 13:23 UTC
