### ISSUE TITLE
Support base via option / configuration

### ISSUE THREAD

**Issue by troyronda** [trustbloc/sidetree-core-go#447] opened 2020-10-26 14:54 UTC
Let's add the `@base` property as an option for the DID document transformation. This capability will allow us to fully test against the sidetree interop fixtures.

We will need this to be configurable since `aries-framework-go` doesn’t currently support it. We should also fix aries-framework-go as a followup.

**Comment by llorllale** [comment] 2020-10-26 18:32
@troyronda 

> We should also fix aries-framework-go as a followup.

Framework parsers should respect the content type.

**Comment by llorllale** [comment] 2020-10-26 18:33
Also this is a duplicate of #370

**Closed** 2020-10-26 18:34 UTC
